### ISSUE TITLE
Make `Base.show` materialize the output of `D(f)(v)`

### ISSUE THREAD

**Issue by MasonProtter** [YingboMa/ForwardDiff2.jl#21]
Currently we have this behaviour:
```julia
using ForwardDiff2: D, DI, I

v = rand(3)

julia> D(cumsum)(v)
 D(cumsum)([0.225954, 0.16515, 0.248423])

julia> DI(cumsum)(v) # D(cumsum)(v) * I
 3×3 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  1.0  0.0  0.0
  1.0  1.0  0.0
  1.0  1.0  1.0
```
I think this lazy solution is nice, but the interface isn't. An easy solution would be to have the derivative materialize once `show`n, or once an algebraic operation is done to it.

**Comment by ChrisRackauckas** [comment]
No, it shouldn't compute anything until the vjp otherwise it'll be using full Jacobians

**Comment by MasonProtter** [comment]
> No, it shouldn't compute anything until the jvp otherwise it'll be using full Jacobians

And? If you don't want a full Jacobian, don't ask for one...

**Comment by ChrisRackauckas** [comment]
But making show takes away that choice. It's a trap, since we have many cases where full Jacobians take 10s of minutes (and more) to compute. Making such a long computation part of the show method will lead to weird stalls where a user quickly constructs the object and then wants to color the Jacobian calculation but then it takes 30 minutes because it accidentally did a show. That kind of behavior isn't nice.

**Comment by oxinabox** [comment]
^ This.

Doing computation in show leads to suffering.

Another point is that
any bug that occur duuring show are really confusing to users.
Because they think the bug happening in the function they just ran.

**Comment by YingboMa** [comment]
Making show potentially expensive is not a good idea.
